#!/usr/bin/env bash
# Creates a PID file and handles SIGTERM and SIGQUIT signals

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM SIGQUIT

while true
do
    sleep 1
done
